// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FansubFileNameParser {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MediaMetadataTags {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaMetadataTags() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FansubFileNameParser.MediaMetadataTags", typeof(MediaMetadataTags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Hi10P {
            get {
                return ResourceManager.GetString("Hi10P", resourceCulture);
            }
        }
        
        internal static string DVD {
            get {
                return ResourceManager.GetString("DVD", resourceCulture);
            }
        }
        
        internal static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        internal static string MP3 {
            get {
                return ResourceManager.GetString("MP3", resourceCulture);
            }
        }
        
        internal static string SevenTwentyP {
            get {
                return ResourceManager.GetString("SevenTwentyP", resourceCulture);
            }
        }
        
        internal static string FourEightyP {
            get {
                return ResourceManager.GetString("FourEightyP", resourceCulture);
            }
        }
        
        internal static string OGG {
            get {
                return ResourceManager.GetString("OGG", resourceCulture);
            }
        }
        
        internal static string EightBitWithSpace {
            get {
                return ResourceManager.GetString("EightBitWithSpace", resourceCulture);
            }
        }
        
        internal static string DVDRIP {
            get {
                return ResourceManager.GetString("DVDRIP", resourceCulture);
            }
        }
        
        internal static string X264 {
            get {
                return ResourceManager.GetString("X264", resourceCulture);
            }
        }
        
        internal static string AAC {
            get {
                return ResourceManager.GetString("AAC", resourceCulture);
            }
        }
        
        internal static string FLAC {
            get {
                return ResourceManager.GetString("FLAC", resourceCulture);
            }
        }
        
        internal static string TenBitWithSpace {
            get {
                return ResourceManager.GetString("TenBitWithSpace", resourceCulture);
            }
        }
        
        internal static string BLURAY {
            get {
                return ResourceManager.GetString("BLURAY", resourceCulture);
            }
        }
        
        internal static string TenBit {
            get {
                return ResourceManager.GetString("TenBit", resourceCulture);
            }
        }
        
        internal static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        internal static string AC3 {
            get {
                return ResourceManager.GetString("AC3", resourceCulture);
            }
        }
        
        internal static string DTS {
            get {
                return ResourceManager.GetString("DTS", resourceCulture);
            }
        }
        
        internal static string EightBit {
            get {
                return ResourceManager.GetString("EightBit", resourceCulture);
            }
        }
        
        internal static string TenEightyP {
            get {
                return ResourceManager.GetString("TenEightyP", resourceCulture);
            }
        }
        
        internal static string BDRIP {
            get {
                return ResourceManager.GetString("BDRIP", resourceCulture);
            }
        }
        
        internal static string XVID {
            get {
                return ResourceManager.GetString("XVID", resourceCulture);
            }
        }
        
        internal static string H264 {
            get {
                return ResourceManager.GetString("H264", resourceCulture);
            }
        }
    }
}
