//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FansubFileNameParser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MediaMetadataTags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaMetadataTags() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FansubFileNameParser.MediaMetadataTags", typeof(MediaMetadataTags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC.
        /// </summary>
        internal static string AAC {
            get {
                return ResourceManager.GetString("AAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC3.
        /// </summary>
        internal static string AC3 {
            get {
                return ResourceManager.GetString("AC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD.
        /// </summary>
        internal static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDRIP.
        /// </summary>
        internal static string BDRIP {
            get {
                return ResourceManager.GetString("BDRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLURAY.
        /// </summary>
        internal static string BLURAY {
            get {
                return ResourceManager.GetString("BLURAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLU-RAY.
        /// </summary>
        internal static string BLURAY_WITH_DASH {
            get {
                return ResourceManager.GetString("BLURAY_WITH_DASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS.
        /// </summary>
        internal static string DTS {
            get {
                return ResourceManager.GetString("DTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD.
        /// </summary>
        internal static string DVD {
            get {
                return ResourceManager.GetString("DVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVDRIP.
        /// </summary>
        internal static string DVDRIP {
            get {
                return ResourceManager.GetString("DVDRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8BIT.
        /// </summary>
        internal static string EightBit {
            get {
                return ResourceManager.GetString("EightBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 BIT.
        /// </summary>
        internal static string EightBitWithSpace {
            get {
                return ResourceManager.GetString("EightBitWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 576I.
        /// </summary>
        internal static string FiveSeventySixInterlaced {
            get {
                return ResourceManager.GetString("FiveSeventySixInterlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 576 I.
        /// </summary>
        internal static string FiveSeventySixInterlacedWithSpace {
            get {
                return ResourceManager.GetString("FiveSeventySixInterlacedWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 576P.
        /// </summary>
        internal static string FiveSeventySixProgressive {
            get {
                return ResourceManager.GetString("FiveSeventySixProgressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 576 P.
        /// </summary>
        internal static string FiveSeventySixProgressiveWithSpace {
            get {
                return ResourceManager.GetString("FiveSeventySixProgressiveWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC.
        /// </summary>
        internal static string FLAC {
            get {
                return ResourceManager.GetString("FLAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 480 I.
        /// </summary>
        internal static string FourEightIWithSpace {
            get {
                return ResourceManager.GetString("FourEightIWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 480I.
        /// </summary>
        internal static string FourEightyI {
            get {
                return ResourceManager.GetString("FourEightyI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 480P.
        /// </summary>
        internal static string FourEightyP {
            get {
                return ResourceManager.GetString("FourEightyP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H264.
        /// </summary>
        internal static string H264 {
            get {
                return ResourceManager.GetString("H264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HI10P.
        /// </summary>
        internal static string Hi10P {
            get {
                return ResourceManager.GetString("Hi10P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        internal static string MP3 {
            get {
                return ResourceManager.GetString("MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGG.
        /// </summary>
        internal static string OGG {
            get {
                return ResourceManager.GetString("OGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 720P.
        /// </summary>
        internal static string SevenTwentyP {
            get {
                return ResourceManager.GetString("SevenTwentyP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10BIT.
        /// </summary>
        internal static string TenBit {
            get {
                return ResourceManager.GetString("TenBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 BIT.
        /// </summary>
        internal static string TenBitWithSpace {
            get {
                return ResourceManager.GetString("TenBitWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1080I.
        /// </summary>
        internal static string TenEightyI {
            get {
                return ResourceManager.GetString("TenEightyI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1080 I.
        /// </summary>
        internal static string TenEightyIWithSpace {
            get {
                return ResourceManager.GetString("TenEightyIWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1080P.
        /// </summary>
        internal static string TenEightyP {
            get {
                return ResourceManager.GetString("TenEightyP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC1.
        /// </summary>
        internal static string VC1 {
            get {
                return ResourceManager.GetString("VC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X264.
        /// </summary>
        internal static string X264 {
            get {
                return ResourceManager.GetString("X264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XVID.
        /// </summary>
        internal static string XVID {
            get {
                return ResourceManager.GetString("XVID", resourceCulture);
            }
        }
    }
}
